create table if not exists public.avaliacoes (
  id bigint generated by default as identity primary key,
  usuario_id text not null,
  academia_id text not null,
  nota numeric(2,1) not null check (nota >= 1 and nota <= 5),
  comentario text,
  created_at timestamptz not null default now()
);

create index if not exists idx_avaliacoes_usuario_id on public.avaliacoes (usuario_id);
create index if not exists idx_avaliacoes_academia_id on public.avaliacoes (academia_id);
